function OutputTogether(layout_path,raw_names)
%% ========================================================================
%  OutputTogether
%  ------------------------------------------------------------------------
%  PURPOSE (plain English, non-proteomics audience):
%    Build a single, human-readable, tab-separated table that consolidates,
%    for ALL samples, the peptide-level quantitative outputs that were
%    previously generated by a histone-proteomics workflow (EpiProfile-like).
%
%    Concretely, this function:
%      1) Counts how many peptide entries (rows) exist by reading ALL .mat
%         files inside the /detail/ folder of the FIRST sample.
%      2) For every sample, stacks three numbers per peptide row:
%            - RT (retention time, minutes)
%            - Area (chromatographic peak area)
%            - Ratio (relative abundance / normalized fraction)
%         into a large matrix 'info' with shape: [nPeptides x (nSamples*3)].
%      3) Writes a tab-separated ".xls" file with an easy-to-scan layout:
%            - Header with sample names repeated three times
%              (for Ratio | Area | RT blocks, in that order).
%            - For each peptide group (i.e., each .mat file):
%                 * First a line with the peptide sequence (and window label),
%                 * Then one line per modified form (mod_short) with the
%                   values per sample:
%                        [all Ratios]  [all Areas]  [all RTs]
%
%  EXPECTED INPUT FILES PER SAMPLE:
%    For each sample i (1-based), the function looks under:
%        <layout_path>/<twoDigitIndex>_<raw_names{i}>/detail/
%      Example:
%        layout_path = '/project/results'
%        raw_names{1} = 'SampleA'
%        folder read: '/project/results/01_SampleA/detail/'
%    Inside 'detail/' there must be many .mat files (one per peptide window).
%
%  WHAT EACH .MAT FILE MUST CONTAIN (minimal):
%    - His : a struct with, at least:
%        * pep_mz   : [nPeptides x 1] precursor m/z per peptide-row
%        * pep_seq  : (char) the peptide sequence for that peptide window
%        * mod_short: {nPeptides x 1} short labels for each modified form
%                    (e.g., 'K9ac', 'K4me1', etc.)
%    - auc : [nPeptides x 3] numeric matrix with columns:
%            (1) RT (retention time, minutes)
%            (2) Area (peak area)
%            (3) Ratio (normalized proportion for that modified form)
%
%  OUTPUT FILE:
%    A single tab-separated text file (with ".xls" extension for convenience):
%      - If the last folder name in layout_path is 'histone_layouts':
%           <parent_of_layout_path>/histone_ratios.xls
%        else:
%           <grandparent>/< 'histone_ratios_' + lastFolder + '.xls'>
%        (See exact code below.)
%
%  COLUMN ORDER IN THE OUTPUT TABLE:
%    Header:
%      [sample1]...[sampleN]   [sample1]...[sampleN]   [sample1]...[sampleN]
%         (for Ratios)            (for Areas)               (for RTs)
%    Row per modification (mod_short) within each peptide group:
%      [all Ratios across samples]   [all Areas across samples]   [all RTs]
%
%  IMPORTANT ASSUMPTION:
%    The list and order of .mat files must be the SAME across all samples,
%    so that stacking works consistently (peptide rows align across samples).
%
%  NOTES:
%    - The ".xls" produced is plain tab-separated text (not a true Excel
%      binary). Excel/LibreOffice can open it easily.
%    - There are special cases for datasets labeled as 'SILAC' or 'C13'
%      (stable isotope workflows): the printed peptide header changes slightly.
%
%  ========================================================================


%% ------------------------------------------------------------------------
% 1) COUNT TOTAL NUMBER OF PEPTIDE ROWS (npeps) USING SAMPLE #1
%    We only read the FIRST sample's /detail/ folder to determine how many
%    peptide rows (sum across all .mat files) we will have. This allows us
%    to preallocate the 'info' matrix without dynamic resizing.
npeps = 0;
i = 1;  % always the first sample for sizing

% Build the "01", "02", ... prefix used in folder naming
cur_rawname = raw_names{i};
if i<10
    prefix = ['0',num2str(i)];
else
    prefix = num2str(i);
end;

% Path to that sample's detail folder
cur_outpath = fullfile(layout_path,[prefix,'_',cur_rawname],'detail');

% List all .mat files in the detail folder
out_file1 = fullfile(cur_outpath,'*.mat');
matfiles = dir(out_file1);

% Sum 'npeps' across all .mat files:
%   each .mat has 'His.pep_mz' with as many rows as modified forms recorded.
for j=1:length(matfiles)
    matfile1 = fullfile(cur_outpath,matfiles(j).name);
    load(matfile1);  % expects 'His' and 'auc'
    npeps = npeps + size(His.pep_mz,1);
end;


%% ------------------------------------------------------------------------
% 2) BUILD THE BIG 'info' MATRIX WITH [RT, Area, Ratio] FOR EVERY SAMPLE
%    Shape: [npeps x (nSamples * 3)]
%    Columns for sample i occupy [(i-1)*3+1 : (i-1)*3+3] in the order:
%       col1 = RT, col2 = Area, col3 = Ratio
info = zeros([npeps,length(raw_names)*3]);

for i=1:length(raw_names)
    % Folder naming for sample i
    cur_rawname = raw_names{i};
    if i<10
        prefix = ['0',num2str(i)];
    else
        prefix = num2str(i);
    end;
    cur_outpath = fullfile(layout_path,[prefix,'_',cur_rawname],'detail');

    % 'm' will track the current row offset inside 'info'
    m = 0;

    % Traverse the SAME 'matfiles' list as above to preserve row ordering
    for j = 1:length(matfiles)
        matfile1 = fullfile(cur_outpath,matfiles(j).name);
        load(matfile1);  % expects 'auc' and 'His'
        nlen = size(His.pep_mz,1);  % number of rows contributed by this file

        % Insert the block of [RT Area Ratio] values for this sample
        info(m+1:m+nlen,(i-1)*3+1:(i-1)*3+3) = auc;
        m = m+nlen;  % advance row offset
    end;
end;


%% ------------------------------------------------------------------------
% 3) PREPARE OUTPUT FILE PATH
%    The final filename depends on the last folder name of 'layout_path'.
[raw_path,fname] = fileparts(layout_path);

% If last folder is literally 'histone_layouts', write one shared name.
% Otherwise, include that last folder name in the filename to distinguish.
if 1==strcmp(fname,'histone_layouts')
    inten_file = fullfile(raw_path,'histone_ratios.xls');
else
    inten_file = fullfile(fileparts(raw_path),['histone_ratios_',fname,'.xls']);
end;

% Try to open the output file for writing (text mode).
fp = fopen(inten_file,'w');
if -1==fp
    % If opening failed, print a message and exit cleanly.
    disp(['can not open: ',inten_file]);
    return;
end;


%% ------------------------------------------------------------------------
% 4) WRITE HEADER LINES
%    We print sample identifiers three times to reflect the three numeric
%    blocks that will appear per row: [Ratio] [Area] [RT].
%
%    Final header layout (two lines):
%      LINE 1:
%        <tab> "1,Sample1" ... <tab> "N,SampleN"   <tab> "1,Sample1" ...   <tab> "1,Sample1" ...
%        (block for Ratios)                         (block for Areas)       (block for RTs)
%
%      LINE 2:
%        "Peptide"  <tab> "Ratio" (N times)  <tab> "Area" (N times) <tab> "RT(min)" (N times)
%
%    NOTE: Keeping the exact printing format used in original code.

%-- First header line: sample indices and names, repeated three times
for i=1:length(raw_names)
    fprintf(fp,'\t%d,%s',i,raw_names{i});
end;
fprintf(fp,'\t');
for i=1:length(raw_names)
    fprintf(fp,'\t%d,%s',i,raw_names{i});
end;
fprintf(fp,'\t');
for i=1:length(raw_names)
    fprintf(fp,'\t%d,%s',i,raw_names{i});
end;
fprintf(fp,'\r\n');

%-- Second header line: column labels for the three numeric blocks
fprintf(fp,'Peptide');
for i=1:length(raw_names)
    fprintf(fp,'\tRatio');
end;
fprintf(fp,'\t');
for i=1:length(raw_names)
    fprintf(fp,'\tArea');
end;
fprintf(fp,'\t');
for i=1:length(raw_names)
    fprintf(fp,'\tRT(min)');
end;
fprintf(fp,'\r\n');


%% ------------------------------------------------------------------------
% 5) ITERATE AGAIN OVER THE FIRST SAMPLE'S .MAT FILES TO PRINT ROW GROUPS
%    The table is grouped by peptide-window (.mat file). For each group:
%      - Print one "header" line with the peptide sequence (+ window label).
%      - Then, for each modified entry (row in 'His'), print a line:
%           * Left cell: either "mod_short" alone (SILAC/C13) or
%             "histone_pos + mod_short" (default),
%           * Then: [all Ratios for all samples], [all Areas], [all RTs]
%
%    IMPORTANT: We only use the FIRST sample to retrieve the peptide labels
%               and grouping structure. The quantitative blocks come from
%               the pre-built 'info' matrix (all samples).
i = 1;
cur_rawname = raw_names{i};
if i<10
    prefix = ['0',num2str(i)];
else
    prefix = num2str(i);
end;
cur_outpath = fullfile(layout_path,[prefix,'_',cur_rawname],'detail');

% 'm' tracks the current global row offset inside 'info'
m = 0;

for j=1:length(matfiles)
    matfile1 = fullfile(cur_outpath,matfiles(j).name);
    load(matfile1);  % loads 'His' (pep_seq, mod_short, pep_mz), 'auc', ...

    % Derive a display name for the peptide-window from the filename
    pepname = matfiles(j).name(1:end-4);

    % Historical naming quirk: if filename begins with 'HH', drop one 'H'.
    if 1==strcmp(pepname(1:2),'HH')
        pepname = pepname(2:end);
    end;

    % Parse underscore-separated parts to extract a "version" token,
    % which may encode histone variant info used to build 'histone_pos'.
    p = strfind(pepname,'_');
    version = pepname(p(1)+1:p(2)-1);

    % Retrieve the last folder name of layout_path (used for SILAC/C13 logic)
    %   'fname' was set earlier by [raw_path,fname] = fileparts(layout_path)

    % Print a "group header" line with the peptide sequence for this window.
    % -- SPECIAL case for isotope labeling datasets:
    %    If fname == 'SILAC' or 'C13', we slightly reformat the sequence.
    if 1==strcmp(fname,'SILAC') || 1==strcmp(fname,'C13')
        % If a specific historical window ('H3_04v3...'), coerce to H33
        % (keeps downstream parsing/labeling consistent for these datasets).
        if 1==strcmp(pepname(1:7),'H3_04v3')
            pep_seq = ['H33',His.pep_seq(3:end)];
        else
            pep_seq = His.pep_seq;
        end;
        fprintf(fp,'%s\r\n',pep_seq);  % group header line (sequence only)
    else
        % DEFAULT: Build a positional tag like "H3v?_start_end" (histone_pos)
        if length(version)>=4
            % Handle 'H3_04v3...' pattern: either take char #4 or #4:end
            if 1==strcmp(pepname(1:7),'H3_04v3')
                version = version(4);
            else
                version = version(4:end);
            end;
            histone_pos = [pepname(1:p(1)-1),version,'_', ...
                           pepname(p(2)+1:p(3)-1),'_',pepname(p(3)+1:end)];
        else
            % No explicit variant: use "H?_start_end"
            histone_pos = [pepname(1:p(1)-1),'_', ...
                           pepname(p(2)+1:p(3)-1),'_',pepname(p(3)+1:end)];
        end;
        % Print group header with peptide sequence and positional tag
        fprintf(fp,'%s(%s)\r\n',His.pep_seq,histone_pos);
    end;

    % How many rows (modified forms) in this peptide-window
    nlen = size(His.pep_mz,1);

    % For each modified form (row in this window), print one table row:
    for ino = m+1:m+nlen

        % Left-most cell: the label for this row (modification)
        %   - For isotope datasets: just 'mod_short'
        %   - Otherwise: 'histone_pos + space + mod_short'
        if 1==strcmp(fname,'SILAC') || 1==strcmp(fname,'C13')
            fprintf(fp,'%s',His.mod_short{ino-m});
        else
            fprintf(fp,'%s %s',histone_pos,His.mod_short{ino-m});
        end;

        % === Print the three numeric blocks from the global 'info' matrix ===
        % Block 1: Ratios for ALL samples (col index = (sample-1)*3 + 3)
        for jno=1:length(raw_names)
            fprintf(fp,'\t%f',info(ino,(jno-1)*3+3));
        end;

        fprintf(fp,'\t');

        % Block 2: Areas for ALL samples (col index = (sample-1)*3 + 2)
        for jno=1:length(raw_names)
            fprintf(fp,'\t%e',info(ino,(jno-1)*3+2));
        end;

        fprintf(fp,'\t');

        % Block 3: RTs for ALL samples (col index = (sample-1)*3 + 1)
        for jno=1:length(raw_names)
            fprintf(fp,'\t%.2f',info(ino,(jno-1)*3+1));
        end;

        fprintf(fp,'\r\n');  % end of this row
    end;

    % Advance global row offset by the size of this peptide-window block
    m = m+nlen;
end;

% Close the output file
fclose(fp);

% ============================== END ======================================
